# Generated by Django 5.0.1 on 2024-05-31 20:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
