# Generated by Django 5.0.1 on 2024-06-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_remove_quotation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='phone_number',
            field=models.CharField(blank=True, default='NULL', max_length=255, null=True),
        ),
    ]
