# Generated by Django 5.0.1 on 2024-06-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_quotation_delete_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='phone_number',
        ),
    ]
