# Generated by Django 5.0.1 on 2024-06-15 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabApp', '0002_rename_report_name_reportfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=254, unique=True)),
                ('test_type', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=50)),
                ('evaluation', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.TextField()),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
