# Generated by Django 5.0.1 on 2024-06-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabApp', '0003_patientreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='patient_email',
            field=models.EmailField(max_length=254),
        ),
    ]
