# Generated by Django 5.0.1 on 2024-06-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabApp', '0004_alter_patientreport_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='payment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
