# Generated by Django 5.0.6 on 2024-06-24 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabApp', '0006_samplegeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.date(2000, 1, 1)),
        ),
    ]
